name: Production Deployment

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Production Deployment
        run: echo "Production Deployment Successful"
